#!/usr/bin/python3.7
import os
import sys
import re
import datetime

VERSION = ""
CONF_DIR = "./testpackages"

def usage():
    print("\n*Usage: cart.py <config_file> <operation>\n")
    print("<config_file> - a file inside '" + CONF_DIR + "' (The '.conf' suffix is optional)")
    print("\tconfig_file - can be passed as argument OR fetched from enviorment variable 'VERSION'\n")
    print("<operation> is either of:\n")
    print("\t'create' - create a new expected results file.")
    print("\t'test' - run tests and compare results now to previously created expected results file.")
    print("\t-(FSDB name in config file) - to preserve current directories/files and run inputs for FILE STATE DB *.tar.gz file given (match with FSDB filename in square brackets in your config file. Note, a dash before the name.")
    print("\n")
    exit(0)

if len(sys.argv) == 2:
    if 'VERSION'  in os.environ.keys():
        VERSION = os.environ['VERSION']
        sys.argv.insert(1, VERSION)
    else:
        usage()
        print("\n*ERR: called with only one argument but no 'VERSION' environment variable set.  To call with a single argument please set 'VERSION' environment variable.\n\n")
elif len(sys.argv) != 3:
    usage()

STATE_DIRS = ("response-interpretations", "cached-lcc-factors", "shared-lists", "conversation-history", "sessions", "tls_csv", "interpretations", "compiled-classes")

CURRENT = False
DIR_STATE = "dir_states"
TEMP_ARCHIVE_UNPACK_DIR = "_temp_arc_unpack"
VCCK_PROGRAM = "./vcck.py"
VCCK_PROGRAM_TEMP = "./vcck-cart-temp.py"

TEST_RESULT_DIR = "results_cart_tests"

TEST_RESULT_DIR = TEST_RESULT_DIR.strip()

if TEST_RESULT_DIR[0] == ".":
    print("*ERR: do not have 'TEST_RESULT_DIR' start with '.'\n")
    exit(0)

if TEST_RESULT_DIR[0] == "/":
    print("*ERR: do not have 'TEST_RESULT_DIR' start with '/'\n")
    exit(0)

rm_prev_outdir = "rm -rf " + TEST_RESULT_DIR
res = os.system(rm_prev_outdir)

if res !=0 :
    print("\n*ERR: error when trying to clean up. Error executing '" + rm_prev_outdir + "'")
    exit(0)

os.mkdir(TEST_RESULT_DIR)

if not os.path.isdir(DIR_STATE):
    os.mkdir(DIR_STATE)
    if not os.path.isdir(DIR_STATE):
        print("\n*ERR: was not able to create directory '" + DIR_STATE + "'")
        exit(1)


def create_area_validation_code(area_to_fsdbs):
    py_code = list() 

    for _area_ in area_to_fsdbs.keys():
        _all_fsdbs = str(area_to_fsdbs[_area_])
        _all_fsdbs =_all_fsdbs.replace('{', '(')
        _all_fsdbs = _all_fsdbs.replace('}', ')')

        py_code.append("if((area == '" + _area_ + "') and (_CART_FILEDB not in " + _all_fsdbs + ")):")
        py_code.append("    return")

    return py_code 


def cleanup_dir():
    for file in ("template_words_file.data", "no-interpretations.data", "llog"):
            if os.path.isfile(file):
                os.remove(file)

                if os.path.isfile(file):
                    print("*ERR: could not remove file '" + file + "'")
                    exit(1)

    for dirtoclear in STATE_DIRS:
        safe_rec_del(dirtoclear)


def backup_existing():
    epoch = str(datetime.datetime.now())
    epoch = epoch.replace(' ','_')
    epoch = epoch.replace(':','_')
    epoch = epoch.replace('-','_')
    epoch = epoch.replace('.','_')

    dirs_to_inc_in_bu = ''
    any = False

    for backupdir in STATE_DIRS:
        if os.path.isdir(backupdir):
            dirs_to_inc_in_bu += backupdir + '/. '
            any = True

    backup_dir_cmd = "tar czf " + DIR_STATE + "/" + epoch + ".tar.gz " + dirs_to_inc_in_bu
    if os.path.isfile("template_words_file.data"):
        backup_dir_cmd += "template_words_file.data"
        any = True

    if not any: return

    re = os.system(backup_dir_cmd)

    print(str(any) + " > " + backup_dir_cmd)

    if re != 0:
        print("\n*ERR: problem backing up directory state")
        exit(1)

def sort_all_files(thedir):
    # sort all files in directory <thedir> recursively.

    for entry in os.listdir(thedir):
        entry_fp = thedir + "/" + entry

        if os.path.isdir(entry_fp):
            sort_all_files(entry_fp)
        else:

            mo = re.match('^(.+)/(.+)$', entry_fp)
            if not bool(mo): continue

            dirpart = mo.group(1)
            filename = mo.group(2)
            temp_sorted_filename = dirpart + "/" + filename + ".ts"
            sort_cmd = "sort " + entry_fp + " > " + temp_sorted_filename
            res = os.system(sort_cmd)

            if res != 0:
                print("*ERR: problem executing '" + sort_cmd + "'")

            try:
                os.remove(entry_fp)

                if os.path.isfile(entry_fp):
                    print("*ERR: error could not remove file '" + entry_fp + "'")
                    exit(0)

            except Exception as ex:
                    print("*ERR: error while trying to remove file '" + entry_fp + "'" + str(ex))

            os.rename(temp_sorted_filename, entry_fp)

            if os.path.isfile(temp_sorted_filename):
                print("*ERR: could not rename file '" + temp_sorted_filename + "' to '" + entry_fp + "'")
                exit(0)


def get_file_list_rec(base, theset, thedir):
    for entry in os.listdir(thedir):
        entry_fp = thedir + "/" + entry

        if os.path.isdir(entry_fp):
            get_file_list_rec(base, theset, entry_fp)
        else:
            mo = re.match('^' + base + '/(.+)$', entry_fp)
            if bool(mo):
                rest = mo.group(1)

            theset.add(rest)


def compare_dirs(dir_a, dir_b):
    files_a = set()
    files_b = set()

    get_file_list_rec(dir_a, files_a, dir_a)
    get_file_list_rec(dir_b, files_b, dir_b)

    issues = list()

    for file_in_a in files_a:
        if not file_in_a in files_b:
            issues.append("\n*ERR: File: '" + file_in_a + "' is in '" + dir_a + "', but not in '" + dir_b + "'")

    for file_in_b in files_b:
        if not file_in_b in files_a:
            issues.append("\n**ERR: File: '" + file_in_b + "' is in '" + dir_b + "', but not in '" + dir_a + "'")

    if len(issues):
        for issue in issues:
            print(issue)
        return False

    DIFF_FN = "diff.txt"
    any_file_diffs = False

    for afile in files_a:

        if os.path.isfile(DIFF_FN):
            os.remove(DIFF_FN)
            if os.path.isfile(DIFF_FN):
                print("\n*ERR: cannot remove '" + DIFF_FN + "'")
                exit(0)

        diff_cmd = "diff " + dir_a + "/" + afile + " " + dir_b + "/" + afile + " > " + DIFF_FN
        res = os.system(diff_cmd)

        if (res != 0) and (res != 256):
            print("\n*ERR: problems running the command '" + diff_cmd + "'\n")
            exit(0)

        diffs = list()

        try:
            with open(DIFF_FN, 'r') as dfh:
                diffs = dfh.readlines()

        except Exception as ex:
            print("\n*ERR: problem loading file '" + DIFF_FN + "'")
            exit(0)

        if len(diffs):
            print("\n*ERR: Different results for file '" + dir_a + "/" + afile + "' -VERSUS- '" + dir_b + "/" + afile + "'")
            print("-----------------------------------------------------------")
            print("                 DIFF OUTPUT                              ")
            print("-----------------------------------------------------------")
            print(diff_cmd)
            print("-----------------------------------------------------------")

            for line in diffs:
                print(line, end="")
            print("-----------------------------------------------------------")
            print("> : Output from this run")
            print("< : Expected results.\n") 
            any_file_diffs = True

    if any_file_diffs:
        return False

    return True


def validate(fp_archive, temp_dir, resdir):
    temp_unarc_cmd = "tar -xzf " + fp_archive  + " -C " + temp_dir
    #print("about to execute : " + temp_unarc_cmd)
    #print("press enter")
    #input()
    print(temp_unarc_cmd)
    #print('enter...')
    #input()

    res = os.system(temp_unarc_cmd)

    #print('hit enter')
    #input()

    if res != 0:
        print("\n*ERR: problem unpacking the archive '" + fp_archive + "'")
        exit(0)
    
    compres = compare_dirs(temp_dir, resdir)

    if compres == True:
        safe_rec_del(temp_dir)

    return compres

def create_dir_if_not_exist(thedir):
    try:
        if not os.path.exists(thedir):
            os.mkdir(thedir)
            if not os.path.exists(thedir):
                print("*ERR: Cannot create directory: " + thedir)
                exit(0)
    except Exception as ex:
        print("*ERR: problem creating directory - " + str(ex))
    return


def safe_rec_del(thedir: str) -> None:
    thedir_stripped = thedir.strip()
    if (thedir_stripped[0] == '.') or (thedir_stripped[0] == '/'):
        print("\n*ERR: refusing to perform rm -rf on dir '" + thedir + "'")
        exit(0)

    rec_del_cmd = "rm -rf " + thedir_stripped
    res = os.system(rec_del_cmd)

    #print(rec_del_cmd)
    if res != 0:
        print("\n*ERR: problem executing '" + rec_del_cmd + "'")
        exit(0)


def load_config(file: str, dir: str) -> None:

    data = list() 
    filedb = None
    areas = set()
    areatofsset = dict()   
 
    LWP = False # LWP = last was pause.
    sline = ""

    with open(file, 'r') as fh:

        for line in fh.readlines():

            templine = line.strip()
            if templine == "": continue
            if templine[0] == '#': continue

            sline = templine

            mo = re.match('^"\s*/', sline)

            if bool(mo):
                print("\n*ERR: not allowed to pass symbols to VCCK. Bad line is '" + sline + "'\n")
                exit(1)

            mo = re.match('^(state_dirs|state_files)\s*=.*', sline)
            if bool(mo): continue

            mo = re.match('^areas\s*=\s*(.+?)\s*$', sline)

            if bool(mo):
                areas_str = mo.group(1).strip()
                listareas = areas_str.split(",")

                for rarea in listareas:
                    rarea = rarea.strip()
                    rarea = rarea.lower()
                    if rarea == "": continue

                    mo2 = re.match('^[a-z]+$', rarea)

                    if not bool(mo2):
                        print("\n*ERR: one of the areas given is invalid ('" + rarea + "') - must be only alphabetical charactors.\n")
                        exit(0)

                    if rarea in areas:
                        print("\n*ERR: area '" + rarea + "' - mentioned more than once.  please correct.\n")
                        exit(0)

                    areas.add(rarea)

                continue

            type = None
            mo = re.match('^\s*([\["])\s*(.+?)\s*[\]"]\s*$', sline)

            if (not bool(mo)) and (sline != '/PAUSE'):
                print("\n*ERR: syntax error with line '" + sline + "' - must be inside square brackets OR inside quotes -- square brackets to specify a file state database and quotes for LUI to process OR '/PAUSE'.\n")
                exit(0)

            if sline == '/PAUSE':
                type = '/PAUSE'
            else: 
                type = mo.group(1)
                item = mo.group(2)

            if type == "[":
               
                item_wp = ""
 
                if filedb != None:
                    if LWP:
                        filedb['input_ordered_list'].append('/PAUSE')
                    data.append(filedb)

                filedb = dict()

                LWP = False

                # seperate filename and list of areas...
                mo_area_fsdbs = re.match('^(.+):(.+)$', item)
                if not(mo_area_fsdbs):
                    print("\n*ERR: specifier ('" + item + "') does not match regex ^(.+):(.+)$ - invalid syntax.  Needs to be <filename.of.tar.gz>:<areas>.\n")
                    exit(0)

                item = mo_area_fsdbs.group(1)
                lst_areas = mo_area_fsdbs.group(2)

                for _area in lst_areas.split(','):
                    if _area not in areas:
                        print("\n*ERR: area given ('" + _area + "') for FSDB '" + item + "' doesn't exist. Make sure to have this area on your 'areas=' line at top of config file.\n")
                        exit(0)

                    if _area not in areatofsset.keys():
                        areatofsset[_area] = set()

                    item_no_ext = item
                    mo_remove_suf = re.match('^(.+)\.tar.gz$', item)
                    if bool(mo_remove_suf):
                        item_no_ext = mo_remove_suf.group(1)

                    (areatofsset[_area]).add(item_no_ext)

                filedb['filename'] = item 

                file_in_fp = dir + "/" + item
                if not os.path.isfile(file_in_fp):
                    print("\n*ERR: file does not exist: '" + file_in_fp + "'\n")
                    exit(0)

                filedb['input_set'] = set()
                filedb['input_ordered_list'] = list()

            else:

                if filedb == None:
                    print("\n*ERR: input specified but no state file given - line is '" + sline + "\n")
                    exit(0)
                else:
                    if type == '/PAUSE' and LWP:
                        print("\n*ERR: cannot have two /PAUSE commands in a row!\n")
                        exit(1)

                    if type == '/PAUSE' and LWP == False:
                        LWP = True
                        continue

                    item_wp = item

                    if LWP:
                        item = "/PAUSE:" + item 

                    LWP = False

                    if item_wp in filedb['input_set']:
                        print("\n*ERR: same input repeated for filedb (" + filedb['filename'] + ")! line is '" + sline + "'.\n")
                        exit(0)
                    else:
                        filedb['input_set'].add(item_wp)
                        filedb['input_ordered_list'].append(item)
        
    if filedb != None:
        if sline == '/PAUSE':
            filedb['input_ordered_list'].append('/PAUSE')
        data.append(filedb)

    return (areas, data, areatofsset)


FILES_IN = CONF_DIR + "/" + "files"

create_dir_if_not_exist(CONF_DIR)
create_dir_if_not_exist(FILES_IN)

CART_INPUT_FILE = "temp_cart_input.txt"

OPERATION = sys.argv[2]
OPERATION = OPERATION.lower()

filename_no_ext_fsdb = ""
filename_with_ext_fsdb = ""

mo = re.match('^-(.+)$', OPERATION)

if bool(mo):
    OPERATION = "current"
    CURRENT = True
    temp_name = mo.group(1)

    mo2 = re.match('^(.+?)\.tar\.gz$', temp_name)
    if bool(mo2):
        filename_with_ext_fsdb = temp_name
        filename_no_ext_fsdb = mo2.group(1)
    else:
        filename_with_ext_fsdb = temp_name + '.tar.gz'
        filename_no_ext_fsdb = temp_name

elif (OPERATION != "create") and (OPERATION != "test"):
    print("\n*ERR: the operation you specified ('" + OPERATION + "') is not valid. Must be either 'create', 'test', or a FSDB in your config file (prefixed with a dash).")
    usage()

TEST_PKG = sys.argv[1]
TEST_PKG_NO_EXT = ""

print("\n------------- VERSION: " + TEST_PKG)
print("------------- OPERATION: " + OPERATION)

if TEST_PKG[-5::] != '.conf':
    TEST_PKG_FP = CONF_DIR + "/" + TEST_PKG + ".conf"
    TEST_PKG_NO_EXT = TEST_PKG
else:
    TEST_PKG_FP = CONF_DIR + "/" + TEST_PKG
    len_minus_ext = len(TEST_PKG) - 5
    TEST_PKG_NO_EXT = TEST_PKG[0:len_minus_ext:1] 

if not os.path.isdir(FILES_IN + "/" + TEST_PKG_NO_EXT):
    print("\n*ERR: directory does not exist - '" + FILES_IN + "/" + TEST_PKG_NO_EXT + ".  Please create.\n")
    exit(0)

if os.path.isfile(TEST_PKG_FP) == False:
    print("\n*ERR: file does not exist: '" + TEST_PKG_FP + "'.\n")
    exit(0)

if not CURRENT:
    backup_existing()
    cleanup_dir()


print('\n--------------- RUNNING TEST PACKAGE: ' + TEST_PKG_NO_EXT + " ---------------\n")
print("OPERATION: " + OPERATION + "\n")

SPECIFIC_FILES_IN = FILES_IN + "/" + TEST_PKG_NO_EXT

(areas, tp, areatofsset) = load_config(TEST_PKG_FP, SPECIFIC_FILES_IN)
if len(areas) == 0:
    print("\n*ERR: config file does not specify any areas.   Please add 'areas=' line.\n")
    exit(0)


cart_area_to_fsdb_validation_code = create_area_validation_code(areatofsset)

# CREATE CART-runnable version of vcck
# OH = output handle

if os.path.isfile(VCCK_PROGRAM_TEMP):
    os.remove(VCCK_PROGRAM_TEMP)
    if os.path.isfile(VCCK_PROGRAM_TEMP):
        print("\n*ERR: I cannot seem to remove the file '" + VCCK_PROGRAM_TEMP + "'.\n")
        exit(0)

code_lines = list()
test_code_lines = list()

try:
    with open(VCCK_PROGRAM, 'r') as IH:
        code_lines = IH.readlines()

except Exception as ex:
    print("\n*ERR: cannot read in the VCCK program code in '" + VCCK_PROGRAM + "' - " + str(ex))
    exit(0)


cart_includes = dict()

line_number_of_id_01 = None
line_number_of_id_02 = None
line_number_of_id_03 = None
line_number_of_id_04 = None
line_number_of_id_05 = None
line_number_of_id_06 = None
line_number_of_id_07 = None
line_number_of_id_08 = None

leading_space_id_01 = ''
leading_space_id_02 = ''
leading_space_id_03 = ''
leading_space_id_04 = ''
leading_space_id_05 = ''
leading_space_id_06 = ''
leading_space_id_07 = ''
leading_space_id_08 = ''

find_include_regex  = r"^(\s*)#\s*CART_INCLUDE_" + TEST_PKG_NO_EXT + "_(.+\.py)$"

for linenum in range(len(code_lines)):
    stline = code_lines[linenum].rstrip()
   
    mo = re.match(find_include_regex, stline)
    if bool(mo):
        ws_for_inc_line = mo.group(1)
        inc_fn = mo.group(2)
        inc_fn_fp = CONF_DIR + "/files/" + TEST_PKG_NO_EXT + "/" + inc_fn

        if not os.path.isfile(inc_fn_fp):
            print("\n*ERR: include file mentioned in line '" + stline + "' does not exist.  - " + inc_fn_fp + " does not exist!\n")
            exit(0)

        try:
            with open(inc_fn_fp, 'r') as fh:
                include_file_lines = fh.readlines()
                cart_includes[linenum] = (ws_for_inc_line, include_file_lines)

        except Exception as ex:
            print("\n*ERR: could not load file '" + inc_fn_fp + "' - check if I have permission to open it.\n")
            exit(0)

    mo = re.match('^(\s*)#\s*__CART_REPLACED_LINE_01_DO_NOT_REMOVE_THIS_LINE\s*$', stline)
    if bool(mo):
        line_number_of_id_01 = linenum
        leading_space_id_01 = mo.group(1)

    mo = re.match('^(\s*)#\s*__CART_REPLACED_LINE_02_DO_NOT_REMOVE_THIS_LINE\s*$', stline)
    if bool(mo):
        line_number_of_id_02 = linenum
        leading_space_id_02 = mo.group(1)

    mo = re.match('^(\s*)#\s*__CART_REPLACED_LINE_03_DO_NOT_REMOVE_THIS_LINE\s*$', stline)
    if bool(mo):
        line_number_of_id_03 = linenum
        leading_space_id_03 = mo.group(1)

    mo = re.match('^(\s*)#\s*__CART_REPLACED_LINE_04_DO_NOT_REMOVE_THIS_LINE\s*$', stline)
    if bool(mo):
        line_number_of_id_04 = linenum
        leading_space_id_04 = mo.group(1)

    mo = re.match('^(\s*)#\s*__CART_REPLACED_LINE_05_DO_NOT_REMOVE_THIS_LINE\s*$', stline)
    if bool(mo):
        line_number_of_id_05 = linenum
        leading_space_id_05 = mo.group(1)

    mo = re.match('^(\s*)#\s*__CART_REPLACED_LINE_06_DO_NOT_REMOVE_THIS_LINE\s*$', stline)
    if bool(mo):
        line_number_of_id_06 = linenum
        leading_space_id_06 = mo.group(1)

    mo = re.match('^(\s*)#\s*__CART_REPLACED_LINE_07_DO_NOT_REMOVE_THIS_LINE\s*$', stline)
    if bool(mo):
        line_number_of_id_07 = linenum
        leading_space_id_07 = mo.group(1)

    mo = re.match('^(\s*)#\s*__CART_REPLACED_LINE_08_DO_NOT_REMOVE_THIS_LINE\s*$', stline)
    if bool(mo):
        line_number_of_id_08 = linenum
        leading_space_id_08 = mo.group(1)


if line_number_of_id_01 == None:
    print("\n*ERR: Anchor text missing in VCCK source code!!! Missing line '__CART_REPLACED_LINE_01_DO_NOT_REMOVE_THIS_LINE'\n")
    exit(0)

if line_number_of_id_02 == None:
    print("\n*ERR: Anchor text missing in VCCK source code!!! Missing line '__CART_REPLACED_LINE_02_DO_NOT_REMOVE_THIS_LINE'\n")
    exit(0)

if line_number_of_id_03 == None:
    print("\n*ERR: Anchor text missing in VCCK source code!!! Missing line '__CART_REPLACED_LINE_03_DO_NOT_REMOVE_THIS_LINE'\n")
    exit(0)

if line_number_of_id_04 == None:
    print("\n*ERR: Anchor text missing in VCCK source code!!! Missing line '__CART_REPLACED_LINE_04_DO_NOT_REMOVE_THIS_LINE'\n")
    exit(0)

if line_number_of_id_05 == None:
    print("\n*ERR: Anchor text missing in VCCK source code!!! Missing line '__CART_REPLACED_LINE_05_DO_NOT_REMOVE_THIS_LINE'\n")
    exit(0)

if line_number_of_id_06 == None:
    print("\n*ERR: Anchor text missing in VCCK source code!!! Missing line '__CART_REPLACED_LINE_06_DO_NOT_REMOVE_THIS_LINE'\n")
    exit(0)

if line_number_of_id_07 == None:
    print("\n*ERR: Anchor text missing in VCCK source code!!! Missing line '__CART_REPLACED_LINE_07_DO_NOT_REMOVE_THIS_LINE'\n")
    exit(0)

if line_number_of_id_08 == None:
    print("\n*ERR: Anchor text missing in VCCK source code!!! Missing line '__CART_REPLACED_LINE_08_DO_NOT_REMOVE_THIS_LINE'\n")
    exit(0)

# create source code for CART-runnable version of vcck !

for linenum in range(len(code_lines)):
    stline = code_lines[linenum].rstrip()

    if linenum == line_number_of_id_01:
        for area in areas:
            test_code_lines.append(leading_space_id_01 + '_cart_area_' + area + ' = None')

    elif linenum == line_number_of_id_02:
        for area in areas:
            test_code_lines.append(leading_space_id_02 + 'global _cart_area_' + area)

    elif linenum == line_number_of_id_03:
        first = True
        for area in areas:
            if first:
                test_code_lines.append(leading_space_id_03 + 'if area == "' + area + '":')
                first = False
            else:
                test_code_lines.append(leading_space_id_03 + 'elif area == "' + area + '":')

            test_code_lines.append(leading_space_id_03 + '    ref = _cart_area_' + area)
            test_code_lines.append(leading_space_id_03 + '    known_area = True') 

    elif linenum == line_number_of_id_04:
        for area in areas:
            test_code_lines.append(leading_space_id_04 + 'if area == "' + area + '": _cart_area_' + area + ' = ref')

    elif linenum == line_number_of_id_05:
        for area in areas:
            test_code_lines.append(leading_space_id_05 + 'if bool(_cart_area_' + area + '):')
            test_code_lines.append(leading_space_id_05 + '    ' + '_cart_area_' + area + '.close()')
            test_code_lines.append(leading_space_id_05 + '    ' + '_cart_area_' + area + ' = None')

    elif linenum == line_number_of_id_06:
        test_code_lines.append(leading_space_id_06 + 'if TESTING:')
        for area in areas:
            test_code_lines.append(leading_space_id_06 + '    if bool(_cart_area_' + area + '):')
            test_code_lines.append(leading_space_id_06 + '        ' + '_cart_area_' + area + '.close()')
            test_code_lines.append(leading_space_id_06 + '        ' + '_cart_area_' + area + ' = None')

    elif linenum == line_number_of_id_07:
        for area_valid_line in cart_area_to_fsdb_validation_code:
            test_code_lines.append(leading_space_id_07 + area_valid_line)

    elif linenum == line_number_of_id_08:
        test_code_lines.append(leading_space_id_08 + 'if(lui == "/PAUSE"):' + "\n") 
        test_code_lines.append(leading_space_id_08 + '    print("\\n\\t\\t* * * CART TESTING PAUSED * * *")')
        test_code_lines.append(leading_space_id_08 + '    print("\\n\\t\\t - press enter to continue -")')
        test_code_lines.append(leading_space_id_08 + '    input()')
        test_code_lines.append(leading_space_id_08 + '    continue')

        test_code_lines.append(leading_space_id_08 + 'mo_swp = re.match("^/PAUSE:(.+)$", lui)')
        test_code_lines.append(leading_space_id_08 + 'if bool(mo_swp):')
        test_code_lines.append(leading_space_id_08 + '    print("\\n\\t\\t* * * CART TESTING PAUSED * * *")')
        test_code_lines.append(leading_space_id_08 + '    print("\\n\\t\\t - press enter to continue -")')
        test_code_lines.append(leading_space_id_08 + '    lui = mo_swp.group(1)')
        test_code_lines.append(leading_space_id_08 + '    print("\\n\\t\\tAfter you press enter, VCCK will process:")')
        test_code_lines.append(leading_space_id_08 + '    print("\\n\\t\\t\t" + lui)')
        test_code_lines.append(leading_space_id_08 + '    input()')

    elif linenum in cart_includes.keys():
        ind_ws = cart_includes[linenum][0]
        for codeline in cart_includes[linenum][1]:
            test_code_lines.append(ind_ws + codeline.rstrip())

    else:
        test_code_lines.append(stline)

try:
    with open(VCCK_PROGRAM_TEMP,'w') as FH:
        for cline in test_code_lines:
            FH.write(cline + "\n")

except Exception as ex:
    print("\n*ERR: issues creating '" + VCCK_PROGRAM_TEMP + "' - " + str(ex))
    exit(0)

# Done - creating cart runnable vcck.

# prev_files = all files from previous tar.gz file. to clean up, so we don't mix up files from 2 different *.tar.gz files.
prev_files = set()
TEMP_CONTENTS_FILE = "state_file_contents.txt"

if os.path.isfile(TEMP_CONTENTS_FILE):
    os.remove(TEMP_CONTENTS_FILE)
    if os.path.isfile(TEMP_CONTENTS_FILE):
        print("\n*ERR: I cannot seem to remove the file '" + TEMP_CONTENTS_FILE + "'.\n")
        exit(0)

if CURRENT:
    outforcurrent = TEST_RESULT_DIR + "/" + filename_no_ext_fsdb
    os.mkdir(outforcurrent)

    if not os.path.isdir(outforcurrent):
        print("\n*ERR: was not able to create '" + outforcurrent + "'")
        exit(1)

    with open(CART_INPUT_FILE, 'w') as fh:
        lineind = 0

        _CART_FILEDB = -1 
        for i in range(len(tp)):
            if tp[i]['filename'] == (filename_no_ext_fsdb + '.tar.gz'):
                _CART_FILEDB = i
                break

        if _CART_FILEDB == -1:
            print("\n*ERR: '" + filename_no_ext_fsdb + "' doesn't exist in your config file!\n")
            exit(0)
        
        for line in tp[int(_CART_FILEDB)]['input_ordered_list']:
            fh.write(line + "\n")
            dir_filedb_linenum = outforcurrent + "/" + str(lineind)
            os.mkdir(dir_filedb_linenum)
            if not os.path.isdir(dir_filedb_linenum):
                print("*ERR: wasn't able to create '" + dir_filedb_linenum + "'.\n")
                exit(0)
            lineind += 1

    make_exec_cmd = "chmod +x " + VCCK_PROGRAM_TEMP
    res = os.system(make_exec_cmd)

    if res != 0:
        print("\n*ERR: problem executing '" + make_exec_cmd + "'")
        exit(1)

    vcck_start_cmd = VCCK_PROGRAM_TEMP + " -T " + filename_no_ext_fsdb + ":" + CART_INPUT_FILE
    print(vcck_start_cmd)

    res = os.system(vcck_start_cmd)

    if res != 0:
        print("\n*ERR: problem running VCCK ('" + vcck_start_cmd + "')")
        exit(1)

    sort_all_files(TEST_RESULT_DIR)
    print("\nDone.  Output from cartlog() calls placed in " + outforcurrent + "\n")
    print("Directory state wasn't changed.\n")
    exit(0)


if len(tp) == 0:
    print("* No file state databases defined in your configuration file. Exiting now.\n")
    exit(0)

for filedbid in range(len(tp)):
    print("Next filedb.  Hit enter to continue:")
    #input()

    for file in prev_files:
        
        file = file.strip()

        if file[0] == '/' or file[0] == '.':
            # directory to remove should not start with / or .
            print("*ERR: ** NO ** refusing to run 'rm -rf " + file + "'")
            exit(0)

        rm_cmd = "rm -rf " + file
        #print(rm_cmd)
        res = os.system(rm_cmd)
        if res != 0:
            print("\n*ERR: trying to execute " + rm_cmd + "'")
            exit(0)

    prev_files = set()
    
    print("----------------------------------------------------------------------------------")
    print("Using State Files in: " + str(filedbid) + ", Db: " + tp[filedbid]['filename']) 
    tar_contents_cmd = "tar tzf " + FILES_IN + "/" + TEST_PKG_NO_EXT + "/" + tp[filedbid]['filename'] + " > " + TEMP_CONTENTS_FILE

    res = os.system(tar_contents_cmd)
 
    if res != 0:
        print("\n*ERR: Problem when executing: '" + tar_contents_cmd + " (make sure you verify cleanup of un-archived files)\n")
        exit(0)

    if not os.path.isfile(TEMP_CONTENTS_FILE):
        print("\n*ERR: The content listing file was not created ('" + TEMP_CONTENTS_FILE + "').\n")
        exit(0)

    with open(TEMP_CONTENTS_FILE, 'r') as fh:
        for line in fh:
            sline = line.strip()

            mo = re.match('^\./(.*)$', sline)
            if bool(mo):
                sline = mo.group(1)

            if sline == '': continue
            if sline[0] == '.': continue

            mo = re.match('^(.+?)/.*$', sline)
            if bool(mo):
                prev_files.add(mo.group(1))
            else:
                prev_files.add(sline)
 
    unarchive_cmd = "tar xzf " + FILES_IN + "/" + TEST_PKG_NO_EXT + "/" + tp[filedbid]['filename']

    res = os.system(unarchive_cmd)
    if res != 0:
        print("\n*ERR: Problem when executing: '" + unarchive_cmd + " (make sure you verify cleanup of un-archived files)\n")
        exit(0)

    res = os.system("sync")
    if res != 0:
        print("\n*ERR: problem running 'sync'.")
        exit(1)
 
    if os.path.isfile(CART_INPUT_FILE):
        os.remove(CART_INPUT_FILE)
        if os.path.isfile(CART_INPUT_FILE):
            print("\n*ERR: cannot remove file '" + CART_INPUT_FILE + "' from last run.")
            exit(0)

    filename_no_ext_fsdb = tp[filedbid]['filename'] 
    mo = re.match('^(.+)\.tar.gz$', filename_no_ext_fsdb)
    if bool(mo):
        filename_no_ext_fsdb = mo.group(1) 

    dir_filedbid = TEST_RESULT_DIR + "/" + filename_no_ext_fsdb
    os.mkdir(dir_filedbid)

    if not os.path.isdir(dir_filedbid):
        print("\n*ERR: could not create directory: '" + dir_filedbid + "'")
        exit(1)
    
    with open(CART_INPUT_FILE, 'w') as fh:
        lineind = 0
     
        for line in tp[filedbid]['input_ordered_list']:
            fh.write(line + "\n")
            dir_filedb_linenum = dir_filedbid + "/" + str(lineind)
            os.mkdir(dir_filedb_linenum)
            lineind += 1 

    make_exec_cmd = "chmod +x " + VCCK_PROGRAM_TEMP
    res = os.system(make_exec_cmd)
    if res != 0:
        print("\n*ERR: problem executing '" + make_exec_cmd + "'")
        exit(0)

    filedbname = tp[filedbid]['filename']
    
    mo = re.match('^(.+?).tar.gz$', filedbname)
    if bool(mo):
        filename_no_ext_fsdb = mo.group(1)
    else:
        print("\n*ERR: strange name: '" + filedbname + "' - should end with tar.gz")
        exit(0)

    vcck_start_cmd = VCCK_PROGRAM_TEMP + " -T " + filename_no_ext_fsdb + ":" + CART_INPUT_FILE
    print(vcck_start_cmd)
    
    res = os.system(vcck_start_cmd)
    
    if res != 0:
        print("\n*ERR: problem running VCCK ('" + vcck_start_cmd + "')")
        exit(0)
    
#print("-ready to remove files. Press enter.")
#input()

for file in prev_files:
    
    file = file.strip()

    if file[0] == '/' or file[0] == '.':
        # directory to remove should not start with / or .
        print("*ERR: ** NO **  refusing to run 'rm -rf " + file + "'")
        exit(0)

    rm_cmd = "rm -rf " + file
    #print(rm_cmd) 
    res = os.system(rm_cmd)
    if res != 0:
        print("\n*ERR: trying to execute '" + rm_cmd + "'")
        exit(0)


temp_file = "vcck-cart-temp.py"
orig_file = "vcck.py"

if os.path.exists(temp_file):
    try:
        os.remove(temp_file)

    except Exception as ex:
        print("*ERR: " + str(ex))

if os.path.exists(temp_file):
    print("*ERR: I was unable to remove previous file '" + temp_file + "' - Stopping the testing.")
    exit()

os.remove(TEMP_CONTENTS_FILE)

if os.path.isfile(CART_INPUT_FILE):
    os.remove(CART_INPUT_FILE)
    if os.path.isfile(CART_INPUT_FILE):
        print("\n*ERR: I was not able to remove file '" + CART_INPUT_FILE + "'")
        exit(0)

#os.remove(VCCK_PROGRAM_TEMP)

safe_rec_del(TEMP_ARCHIVE_UNPACK_DIR)
os.mkdir(TEMP_ARCHIVE_UNPACK_DIR)

if not os.path.isdir(TEMP_ARCHIVE_UNPACK_DIR):
    print("\n*ERR: could not create '" + TEMP_ARCHIVE_UNPACK_DIR + "'")
    exit(0)

if OPERATION == "create":
    new_archive = CONF_DIR + "/files/" + TEST_PKG_NO_EXT + "/" + TEST_PKG_NO_EXT + ".tar.gz"

    if os.path.isfile(new_archive):
        os.remove(new_archive)
        if os.path.isfile(new_archive):
            print("\n*ERR: I was not able to remove the file '" + new_archive + "' from last run!\n")
            exit(0)

    sort_all_files(TEST_RESULT_DIR)

    tar_create_cmd = "tar -C " + TEST_RESULT_DIR + " -czf " + new_archive + " ."
    res = os.system(tar_create_cmd)

    if res != 0:
        print("\n*ERR: problems when trying to create archive.  Error executing: " + tar_create_cmd)
        exit(0)

    valres = validate(new_archive, TEMP_ARCHIVE_UNPACK_DIR, TEST_RESULT_DIR)

    if valres == False:
        print("*ERROR: Failed to create The expected results archive !!!!!!!!!!!! Bad!")
        sys.exit(0)

    cleanup_dir()
    print("\n*Great! Expected test result archive created successfully.: " + new_archive + "\n")

else:
    existing_archive = CONF_DIR + "/files/" + TEST_PKG_NO_EXT + "/" + TEST_PKG_NO_EXT + ".tar.gz"
    if not os.path.isfile(existing_archive):
        print("\n*ERR: Archive '" + existing_archive + "' does not exist.  Did you run a 'create' yet?")
        exit(0)

    sort_all_files(TEST_RESULT_DIR)

    valres = validate(existing_archive, TEMP_ARCHIVE_UNPACK_DIR, TEST_RESULT_DIR)    

    if valres == True:
        print("\n---------------------------------------------------")
        print("* Regression testing * PASSED *")
        print("---------------------------------------------------")
        cleanup_dir()
    else:
        print("\n---------------------------------------------------")
        print("* Regression testing * F A I L E D*")
        print("---------------------------------------------------")

