TERM: [abc def ghi], NEW:[False], ID:[6]
TERM: [abc def], NEW:[False], ID:[1]
TERM: [def ghi], NEW:[False], ID:[9]
TERM: [ghi], NEW:[False], ID:[2]
TERM: [ghij xox], NEW:[True], ID:[12]
TERM: [ghij], NEW:[False], ID:[7]
TERM: [victor and melanie], NEW:[True], ID:[11]
TERM: [x], NEW:[False], ID:[3]
TERM: [xx], NEW:[True], ID:[13]
TERM: [y], NEW:[False], ID:[4]
TERM: [yy], NEW:[False], ID:[8]
TERM: [z], NEW:[False], ID:[5]
TERM: [ziz], NEW:[True], ID:[14]
TERM: [zz], NEW:[False], ID:[10]
